### ISSUE TITLE
k8s: Is cluster-admin required? What's the minimum needed?

### ISSUE THREAD

**Issue by stephlocke** [openanalytics/shinyproxy-config-examples#13]
In the shinyproxy-config-examples/03-containerized-kubernetes/sp-authorization.yaml file, you grant cluster-admin to shinyproxy.

Is this needed to be able to run shinyproxy pods in kubernetes? Is there a lower level of privilege possible here?

**Comment by dseynaev** [comment]
Hi @stephlocke,

cluster-admin is only bound here to keep the example concise.
Best-practice would be to add a service account and reference it via `serviceAccountName` in the deployment spec.

The following role is the minimal set of permissions:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: example
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
