### ISSUE TITLE
Use properties of `template-groups` in custom templates

### ISSUE THREAD

**Issue by DzimitryM** [openanalytics/shinyproxy-config-examples#40]
How can the properties defined in the `template-groups` be used in the HTML templates?

Let's say the properties are defined in `application.yml`:
```
proxy:
  template-groups:
    - id: tools
      properties:
        display-name: Tools
        maintainer: Tesla
        logo-url: file:////path/to/tools/templates/logo.png
```

To use them in `index.html` one can call the property with `${group.properties.get('maintainer')}` according to the documentation:
```
<!-- Part that shows a list when none of the apps contain a logo -->
<div class="container-fluid">
    <th:block th:each="group: ${templateGroups}">
        <h2 th:text="${group.properties.get('display-name')}"></h2>
        <b>Maintainer: <th:block th:text="${group.properties.get('maintainer')}"/></b>
        <ul class="list-group">
            <th:block th:each="app: ${groupedApps.get(group.id)}" th:include="index :: app(${app})"/>
        </ul>
    </th:block>
 </div>
```

**My question is how to call the properties in the other template files, e.g. `navbar.html`, `modal.html`, when the particular app has been loaded?**

I am trying to resolve the following use case: display different logos depending on the properties of the `template-group` in the navbar.

**Comment by LEDfan** [comment]
Hi, starting with ShinyProxy 3.1.0, you can now use the `apps`, `templateGroups`, `groupedApps` and `ungroupedApps` variables in all templates and pages. Could you have a look whether this solves your use-case?

**Comment by DzimitryM** [comment]
Thank you, @LEDfan . This is an amazing release!

I was able to set a specific Logo and favicon to each app with _shinyproxy 3.1.1_. I didn't use template groups for that, just app specifications. However, a small trick was needed to replace the general title and logo with the app-specific title and logo. My settings are:

**(1) `application.yml`**
```
proxy:
  template-path: /path/to/templates/
  specs:
    - id: software1
      display-name: Application 1
      access-groups: [USERS_1, ADMINS]
      logo-url: file:////path/to/templates/logo_1.png
      favicon-path: /path/to/templates/favicon_1.png
    - id: software2
      display-name: Application 2
      access-groups: [USERS_2, ADMINS]
      logo-url: file:////path/to/templates/logo_2.png
      favicon-path: /path/to/templates/favicon_2.png
```
**(2) Modify `/path/to/templates/navbar.html`**
It should be noted that the `favicon-path` in app specification overrides `proxy.favicon-path`, while the app name and app logo in the navigation bar are taken from `proxy.title` and `proxy.logo-url` by default. So, to have a specific logo and a specific title on the application load, we need to modify the template.

original html:
```
...
	<div class="navbar-header">
		<img class="navbar-brand" th:src="${logo}"/>
		<a class="navbar-brand" th:href="@{/}" th:text="${title}"></a>
	</div>
...
```

modified version:
```
...
	<div class="navbar-header">
		<!-- Show app-related logo -->
		<img class="navbar-brand" th:each="app: ${apps}" th:if="${app.id} == ${appName}" th:src="${appLogos.get(app).src}"/>
		<!-- Show app-related title, or show general title if the app title is not available -->
		<a class="navbar-title" th:href="@{/}" th:text="${appTitle == null} ? ${title} : ${appTitle}"></a>
	</div>
...
```
